//! Centralised filesystem path resolution.
//!
//! Every module that needs to read or write an app file goes through here, so
//! there's one place to change if the layout ever moves. The directory layout
//! mirrors the existing C# Spool app so an existing user's library and config
//! are picked up automatically on first launch.

use std::path::PathBuf;

/// Root data directory: `%LOCALAPPDATA%\Spool` on Windows,
/// `~/.local/share/Spool` on Linux, `~/Library/Application Support/Spool` on macOS.
pub fn app_data_dir() -> PathBuf {
    dirs::data_local_dir()
        .expect("local data dir must be resolvable")
        .join("Spool")
}

pub fn library_file() -> PathBuf {
    app_data_dir().join("library.json")
}

#[allow(dead_code)]
pub fn config_file() -> PathBuf {
    app_data_dir().join("config.json")
}

#[allow(dead_code)]
pub fn covers_dir() -> PathBuf {
    app_data_dir().join("covers")
}

#[allow(dead_code)]
pub fn launchers_dir() -> PathBuf {
    app_data_dir().join("launchers")
}

/// Root for per-game Proton/Wine prefixes (Linux). Each game gets a
/// `<id>` subdir used as `WINEPREFIX` and as ludusavi's `--wine-prefix`.
#[allow(dead_code)]
pub fn proton_prefixes_dir() -> PathBuf {
    app_data_dir().join("prefixes")
}

/// Fixed-path wrapper script that external launchers (Steam shortcuts, Armoury
/// Crate stubs) point at when Spool runs as an AppImage. See
/// [`spool_executable`] for why the AppImage path itself can't be used.
pub fn appimage_launcher_script() -> PathBuf {
    app_data_dir().join("spool-launcher.sh")
}

/// If running as an AppImage, (re)write the stable launcher wrapper so it execs
/// the *current* AppImage. Called at startup so the wrapper self-heals when the
/// AppImage path changes (version bump, AppImageLauncher relocation). No-op when
/// not running as an AppImage. Returns the wrapper path when written.
pub fn refresh_appimage_launcher() -> Option<PathBuf> {
    let appimage = std::env::var_os("APPIMAGE")?;
    let appimage = PathBuf::from(appimage);
    if appimage.as_os_str().is_empty() || !appimage.is_file() {
        return None;
    }
    let script = appimage_launcher_script();
    if let Some(parent) = script.parent() {
        std::fs::create_dir_all(parent).ok()?;
    }
    // Escape embedded double-quotes for the sh string literal (paths with `"`
    // are vanishingly rare but cheap to handle).
    let target = appimage.to_string_lossy().replace('"', "\\\"");
    let body = format!("#!/bin/sh\n# Auto-generated by Spool — execs the current AppImage.\nexec \"{target}\" \"$@\"\n");
    std::fs::write(&script, body).ok()?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755));
    }
    Some(script)
}

/// Path to Spool's own executable as it should be referenced from *outside*
/// the running process — i.e. what external launchers (Steam shortcuts,
/// Armoury Crate stubs) should point at.
///
/// When running as an AppImage, `std::env::current_exe()` returns the
/// ephemeral FUSE-mount path (`/tmp/.mount_SpoolXXXX/usr/bin/spool`), and even
/// `$APPIMAGE` is volatile — the filename carries the version and
/// AppImageLauncher relocates it to `~/Applications/` with a content hash, so
/// it changes on every update. So for AppImage installs we return the stable
/// wrapper script ([`refresh_appimage_launcher`]) instead, which forwards to
/// whatever AppImage is current. Native installs (`/usr/bin/spool`) and Windows
/// return `current_exe()` directly — already stable.
pub fn spool_executable() -> Option<PathBuf> {
    if std::env::var_os("APPIMAGE").is_some() {
        let script = appimage_launcher_script();
        if script.is_file() {
            return Some(script);
        }
        if let Some(s) = refresh_appimage_launcher() {
            return Some(s);
        }
    }
    std::env::current_exe().ok()
}

/// Spool-owned ludusavi configuration directory. Passed to every ludusavi
/// invocation via `--config` so Spool controls backup path, cloud remote,
/// and (cross-device) restore redirects without touching the user's own
/// ludusavi config.
#[allow(dead_code)]
pub fn ludusavi_config_dir() -> PathBuf {
    app_data_dir().join("ludusavi")
}

#[allow(dead_code)]
pub fn ludusavi_config_file() -> PathBuf {
    ludusavi_config_dir().join("config.yaml")
}

/// Persistent log file for `tracing` output. Matches the C# app's path so
/// users (and we) know where to look when something goes wrong. The path
/// is constructed inline in `init_tracing` for the appender's
/// directory-plus-filename API; this helper is kept available for future
/// callers (e.g. a "show debug log" menu item).
#[allow(dead_code)]
pub fn log_file() -> PathBuf {
    app_data_dir().join("debug.log")
}

/// Legacy data root used by the C# `ludusavi-wrap` builds before the
/// Spool rename. Migration looks here to pick up an existing user's
/// config + library on first launch.
fn legacy_ludusavi_wrap_dir() -> Option<PathBuf> {
    dirs::data_local_dir().map(|d| d.join("ludusavi-wrap"))
}

/// One-shot migration of pre-rename data from `%LOCALAPPDATA%\
/// ludusavi-wrap` into `%LOCALAPPDATA%\Spool`. Runs at startup, before
/// `Config::load` and `Library::load`, so the loaded state already
/// reflects the migrated files. Idempotent via a `.migrated-from-
/// ludusavi-wrap` marker dropped into the new dir on first attempt.
///
/// Rules:
///   * no legacy dir → nothing to do (fresh installs, non-Windows)
///   * marker exists → already ran, never re-migrate
///   * Spool dir already has a `library.json` → user has been running
///     Spool already; refuse to overwrite, just lay down the marker
///     so we stop checking
///   * otherwise → copy every file/folder under the legacy dir into
///     Spool's dir, preserving structure
///
/// Best-effort: a failure here is logged but doesn't fail the app.
/// Worst case the user has both directories and has to point Spool
/// at the right ludusavi.exe manually.
pub fn migrate_from_ludusavi_wrap() {
    let Some(old) = legacy_ludusavi_wrap_dir() else {
        return;
    };
    if !old.is_dir() {
        return;
    }
    let new = app_data_dir();
    let marker = new.join(".migrated-from-ludusavi-wrap");
    if marker.exists() {
        return;
    }

    // Ensure the destination exists for the marker write either way.
    if let Err(e) = std::fs::create_dir_all(&new) {
        tracing::warn!(error = %e, "migration: create Spool dir failed");
        return;
    }

    // If Spool already has a library, don't overwrite — drop a marker
    // so we don't keep checking each launch.
    let has_library = new.join("library.json").is_file();
    if has_library {
        let _ = std::fs::write(&marker, "skipped: Spool dir already populated");
        tracing::info!("migration: Spool dir already has library.json, skipping");
        return;
    }

    match copy_dir_contents(&old, &new) {
        Ok(n) => {
            tracing::info!(files = n, "migration: copied {n} files from ludusavi-wrap");
        }
        Err(e) => {
            tracing::warn!(error = %e, "migration: partial copy from ludusavi-wrap");
        }
    }
    let _ = std::fs::write(&marker, "ok");
}

/// Recursive copy of every file under `src` into `dst`, preserving
/// directory structure. Returns the number of files written. Skips
/// hidden / metadata-only entries that wouldn't help the user
/// (`.bak`, `.tmp`).
fn copy_dir_contents(src: &std::path::Path, dst: &std::path::Path) -> std::io::Result<usize> {
    let mut count = 0;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let name = entry.file_name();
        let from = entry.path();
        let to = dst.join(&name);

        if file_type.is_dir() {
            std::fs::create_dir_all(&to)?;
            count += copy_dir_contents(&from, &to)?;
        } else if file_type.is_file() {
            // Skip noisy junk that just inflates the new dir.
            let n = name.to_string_lossy();
            if n.ends_with(".tmp") || n.ends_with(".bak") {
                continue;
            }
            std::fs::copy(&from, &to)?;
            count += 1;
        }
    }
    Ok(count)
}

pub fn resolve_sidecar_path(name: &str) -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let dir = exe.parent()?;
    let exe_ext = if cfg!(windows) { ".exe" } else { "" };

    // 1. Try with target triple suffix (development / target/debug / unpackaged release)
    let triple = target_triple();
    let name_with_triple = format!("{}-{}{}", name, triple, exe_ext);
    let dev_path = dir.join(name_with_triple);
    if dev_path.is_file() {
        return Some(dev_path);
    }

    // 2. Try without target triple suffix (production / packaged release)
    let prod_name = format!("{}{}", name, exe_ext);
    let prod_path = dir.join(prod_name);
    if prod_path.is_file() {
        return Some(prod_path);
    }

    None
}

pub fn resolve_ludusavi_path(configured_path: &str) -> Option<std::path::PathBuf> {
    if !configured_path.is_empty() && std::path::PathBuf::from(configured_path).is_file() {
        Some(std::path::PathBuf::from(configured_path))
    } else if let Some(bundled) = resolve_sidecar_path("ludusavi") {
        Some(bundled)
    } else {
        find_system_binary("ludusavi")
    }
}

pub fn resolve_rclone_path(configured_path: &str) -> Option<std::path::PathBuf> {
    if !configured_path.is_empty() && std::path::PathBuf::from(configured_path).is_file() {
        Some(std::path::PathBuf::from(configured_path))
    } else if let Some(bundled) = resolve_sidecar_path("rclone") {
        Some(bundled)
    } else {
        find_system_binary("rclone")
    }
}

pub fn find_system_binary(name: &str) -> Option<std::path::PathBuf> {
    let exe_name = if cfg!(windows) { format!("{}.exe", name) } else { name.to_string() };

    // Check PATH
    if let Some(path_env) = std::env::var_os("PATH") {
        for dir in std::env::split_paths(&path_env) {
            let candidate = dir.join(&exe_name);
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

fn target_triple() -> &'static str {
    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    return "x86_64-unknown-linux-gnu";
    #[cfg(all(target_os = "linux", target_arch = "aarch64"))]
    return "aarch64-unknown-linux-gnu";
    #[cfg(all(target_os = "windows", target_arch = "x86_64"))]
    return "x86_64-pc-windows-msvc";
    #[cfg(all(target_os = "windows", target_arch = "x86"))]
    return "i686-pc-windows-msvc";
    #[cfg(all(target_os = "macos", target_arch = "x86_64"))]
    return "x86_64-apple-darwin";
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    return "aarch64-apple-darwin";
    #[cfg(not(any(
        all(target_os = "linux", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "aarch64"),
        all(target_os = "windows", target_arch = "x86_64"),
        all(target_os = "windows", target_arch = "x86"),
        all(target_os = "macos", target_arch = "x86_64"),
        all(target_os = "macos", target_arch = "aarch64"),
    )))]
    return "unknown";
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolve_ludusavi_prefers_a_valid_configured_path() {
        // Phase 5 resolution order: config override → bundled → system.
        // A configured path pointing at a real file must win outright.
        let dir = tempfile::tempdir().unwrap();
        let bin = dir.path().join("ludusavi-custom");
        std::fs::write(&bin, b"#!/bin/sh\n").unwrap();

        let resolved = resolve_ludusavi_path(&bin.to_string_lossy());
        assert_eq!(resolved, Some(bin));
    }

    #[test]
    fn resolve_ludusavi_ignores_a_configured_path_that_is_not_a_file() {
        // A stale/non-existent override must fall through to bundled/system
        // discovery rather than being returned as-is. We can't assert what
        // gets found here, only that the bogus override is never returned.
        let bogus = "/nonexistent/path/to/ludusavi";
        let resolved = resolve_ludusavi_path(bogus);
        assert_ne!(
            resolved.as_deref(),
            Some(std::path::Path::new(bogus)),
            "a non-file override must not be returned verbatim",
        );
    }

    #[test]
    fn resolve_rclone_prefers_a_valid_configured_path() {
        let dir = tempfile::tempdir().unwrap();
        let bin = dir.path().join("rclone-custom");
        std::fs::write(&bin, b"#!/bin/sh\n").unwrap();
        assert_eq!(resolve_rclone_path(&bin.to_string_lossy()), Some(bin));
    }

    #[test]
    fn resolve_rclone_ignores_a_configured_path_that_is_not_a_file() {
        let bogus = "/nonexistent/path/to/rclone";
        assert_ne!(
            resolve_rclone_path(bogus).as_deref(),
            Some(std::path::Path::new(bogus)),
        );
    }

    #[test]
    fn resolve_sidecar_returns_none_for_unknown_binary() {
        // Resolution is relative to the test runner's exe dir; a made-up name
        // must never resolve there.
        assert!(resolve_sidecar_path("definitely-not-a-real-sidecar").is_none());
    }
}
